// Shared Vertex AI helper for Supabase Edge Functions
// Uses service account JWT (RS256) + OAuth to call Vertex AI Enterprise (Gemini)

export function base64UrlEncode(input: string | ArrayBuffer): string {
  const bytes =
    typeof input === 'string'
      ? new TextEncoder().encode(input)
      : new Uint8Array(input);

  let binary = '';
  for (const byte of bytes) {
    binary += String.fromCharCode(byte);
  }

  return btoa(binary)
    .replace(/\+/g, '-')
    .replace(/\//g, '_')
    .replace(/=+$/g, '');
}

export function pemToArrayBuffer(pem: string): ArrayBuffer {
  const normalizedPem = pem.replace(/\\n/g, '\n');
  const base64 = normalizedPem
    .replace(/-----BEGIN PRIVATE KEY-----/g, '')
    .replace(/-----END PRIVATE KEY-----/g, '')
    .replace(/\s/g, '');
  const binary = atob(base64);
  const bytes = new Uint8Array(binary.length);

  for (let i = 0; i < binary.length; i++) {
    bytes[i] = binary.charCodeAt(i);
  }

  return bytes.buffer;
}

export async function getVertexAccessToken(): Promise<string> {
  const clientEmail = Deno.env.get('VERTEX_CLIENT_EMAIL');
  const privateKey = Deno.env.get('VERTEX_PRIVATE_KEY');

  if (!clientEmail || !privateKey) {
    throw new Error('Vertex service account credentials not configured');
  }

  const now = Math.floor(Date.now() / 1000);
  const header = { alg: 'RS256', typ: 'JWT' };
  const payload = {
    iss: clientEmail,
    scope: 'https://www.googleapis.com/auth/cloud-platform',
    aud: 'https://oauth2.googleapis.com/token',
    iat: now,
    exp: now + 3600,
  };

  const unsignedJwt = `${base64UrlEncode(JSON.stringify(header))}.${base64UrlEncode(JSON.stringify(payload))}`;

  const key = await crypto.subtle.importKey(
    'pkcs8',
    pemToArrayBuffer(privateKey),
    { name: 'RSASSA-PKCS1-v1_5', hash: 'SHA-256' },
    false,
    ['sign']
  );

  const signature = await crypto.subtle.sign(
    'RSASSA-PKCS1-v1_5',
    key,
    new TextEncoder().encode(unsignedJwt)
  );

  const jwt = `${unsignedJwt}.${base64UrlEncode(signature)}`;

  const tokenResponse = await fetch('https://oauth2.googleapis.com/token', {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    body: new URLSearchParams({
      grant_type: 'urn:ietf:params:oauth:grant-type:jwt-bearer',
      assertion: jwt,
    }),
  });

  if (!tokenResponse.ok) {
    const errorText = await tokenResponse.text();
    console.error('[vertex-ai] OAuth error:', tokenResponse.status, errorText);
    throw new Error(`Vertex OAuth error: ${tokenResponse.status}`);
  }

  const tokenData = await tokenResponse.json();
  if (!tokenData.access_token) {
    throw new Error('Vertex OAuth access_token not returned');
  }

  return tokenData.access_token;
}

/**
 * Generic Vertex AI generateContent call.
 * Accepts an optional systemInstruction for system-level context.
 * Returns the generated text from the first candidate.
 */
export async function callVertexAI(
  prompt: string,
  systemInstruction?: string
): Promise<string> {
  const projectId = Deno.env.get('VERTEX_PROJECT_ID');
  const location = Deno.env.get('VERTEX_LOCATION');
  const model = Deno.env.get('VERTEX_MODEL');

  if (!projectId || !location || !model) {
    throw new Error('Vertex configuration not configured (VERTEX_PROJECT_ID / VERTEX_LOCATION / VERTEX_MODEL)');
  }

  const accessToken = await getVertexAccessToken();

  const requestBody: Record<string, unknown> = {
    contents: [{ role: 'user', parts: [{ text: prompt }] }],
    generationConfig: { temperature: 0.7 },
  };

  if (systemInstruction) {
    requestBody.systemInstruction = {
      parts: [{ text: systemInstruction }],
    };
  }

  const response = await fetch(
    `https://aiplatform.googleapis.com/v1/projects/${projectId}/locations/${location}/publishers/google/models/${model}:generateContent`,
    {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${accessToken}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(requestBody),
    }
  );

  if (!response.ok) {
    const errorText = await response.text();
    console.error('[vertex-ai] generateContent error:', response.status, errorText);
    throw new Error(`Vertex generateContent error: ${response.status}`);
  }

  const data = await response.json();
  const generatedText = data.candidates?.[0]?.content?.parts
    ?.map((part: { text?: string }) => part.text ?? '')
    .join('');

  if (!generatedText) {
    throw new Error('No text generated by Vertex AI');
  }

  return generatedText;
}

/**
 * Vertex AI generateContent call with native tool declarations.
 * Used by functions that need structured output via function calling.
 *
 * @param contents  - Array of Vertex AI content objects (role + parts)
 * @param tools     - Array of Vertex AI tool declarations ({ functionDeclarations: [...] })
 * @param systemInstruction - Optional system-level instruction text
 * @param generationConfig  - Optional generation config overrides
 * @returns The raw Vertex AI response JSON
 */
export async function callVertexAIWithTools(
  contents: VertexContent[],
  tools: VertexTool[],
  systemInstruction?: string,
  generationConfig?: Record<string, unknown>
): Promise<VertexGenerateContentResponse> {
  const projectId = Deno.env.get('VERTEX_PROJECT_ID');
  const location = Deno.env.get('VERTEX_LOCATION');
  const model = Deno.env.get('VERTEX_MODEL');

  if (!projectId || !location || !model) {
    throw new Error('Vertex configuration not configured (VERTEX_PROJECT_ID / VERTEX_LOCATION / VERTEX_MODEL)');
  }

  const accessToken = await getVertexAccessToken();

  const requestBody: Record<string, unknown> = {
    contents,
    tools,
    generationConfig: generationConfig ?? { temperature: 0.7 },
  };

  if (systemInstruction) {
    requestBody.systemInstruction = {
      parts: [{ text: systemInstruction }],
    };
  }

  const response = await fetch(
    `https://aiplatform.googleapis.com/v1/projects/${projectId}/locations/${location}/publishers/google/models/${model}:generateContent`,
    {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${accessToken}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(requestBody),
    }
  );

  if (!response.ok) {
    const errorText = await response.text();
    console.error('[vertex-ai] generateContent (tools) error:', response.status, errorText);
    throw new Error(`Vertex generateContent error: ${response.status}`);
  }

  return response.json() as Promise<VertexGenerateContentResponse>;
}

/**
 * Transcribe audio using Vertex AI Gemini's native multimodal capability.
 * Accepts an ArrayBuffer of audio data and returns the transcribed text.
 */
export async function transcribeAudioVertex(
  audioBuffer: ArrayBuffer,
  mimeType = 'audio/ogg'
): Promise<string | null> {
  const projectId = Deno.env.get('VERTEX_PROJECT_ID');
  const location = Deno.env.get('VERTEX_LOCATION');
  const model = Deno.env.get('VERTEX_MODEL');

  if (!projectId || !location || !model) {
    throw new Error('Vertex configuration not configured');
  }

  const accessToken = await getVertexAccessToken();

  // Convert ArrayBuffer to base64
  const bytes = new Uint8Array(audioBuffer);
  let binary = '';
  for (const byte of bytes) {
    binary += String.fromCharCode(byte);
  }
  const base64Audio = btoa(binary);

  const requestBody = {
    contents: [
      {
        role: 'user',
        parts: [
          {
            inlineData: {
              mimeType,
              data: base64Audio,
            },
          },
          {
            text: 'Transcreva o áudio acima para texto em português brasileiro. Retorne apenas o texto transcrito, sem comentários adicionais.',
          },
        ],
      },
    ],
    generationConfig: { temperature: 0 },
  };

  const response = await fetch(
    `https://aiplatform.googleapis.com/v1/projects/${projectId}/locations/${location}/publishers/google/models/${model}:generateContent`,
    {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${accessToken}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(requestBody),
    }
  );

  if (!response.ok) {
    const errorText = await response.text();
    console.error('[vertex-ai] transcribeAudio error:', response.status, errorText);
    return null;
  }

  const data = await response.json();
  const transcription = data.candidates?.[0]?.content?.parts
    ?.map((part: { text?: string }) => part.text ?? '')
    .join('');

  return transcription || null;
}

// ---------------------------------------------------------------------------
// Type helpers for Vertex AI native API
// ---------------------------------------------------------------------------

export interface VertexPart {
  text?: string;
  inlineData?: { mimeType: string; data: string };
  functionCall?: { name: string; args: Record<string, unknown> };
  functionResponse?: { name: string; response: Record<string, unknown> };
}

export interface VertexContent {
  role: 'user' | 'model';
  parts: VertexPart[];
}

export interface VertexFunctionDeclaration {
  name: string;
  description: string;
  parameters: Record<string, unknown>;
}

export interface VertexTool {
  functionDeclarations: VertexFunctionDeclaration[];
}

export interface VertexCandidate {
  content: VertexContent;
  finishReason?: string;
}

export interface VertexGenerateContentResponse {
  candidates?: VertexCandidate[];
}

/**
 * Extract function calls from a Vertex AI response.
 * Returns an array of { name, args } objects (mirrors OpenAI tool_calls structure).
 */
export function extractFunctionCalls(
  response: VertexGenerateContentResponse
): Array<{ name: string; args: Record<string, unknown> }> {
  const parts = response.candidates?.[0]?.content?.parts ?? [];
  return parts
    .filter((p) => p.functionCall)
    .map((p) => ({
      name: p.functionCall!.name,
      args: p.functionCall!.args ?? {},
    }));
}

/**
 * Convert an OpenAI-style messages array (role: system/user/assistant + content: string)
 * into a Vertex AI contents array (role: user/model) plus a systemInstruction string.
 *
 * Rules:
 * - system messages are merged into a single systemInstruction string
 * - user  messages → role: 'user'
 * - assistant messages → role: 'model'
 */
export function openAiMessagesToVertex(
  messages: Array<{ role: string; content: string }>
): { contents: VertexContent[]; systemInstruction?: string } {
  const systemParts: string[] = [];
  const contents: VertexContent[] = [];

  for (const msg of messages) {
    if (msg.role === 'system') {
      systemParts.push(msg.content);
    } else {
      const role: 'user' | 'model' = msg.role === 'assistant' ? 'model' : 'user';
      contents.push({ role, parts: [{ text: msg.content }] });
    }
  }

  return {
    contents,
    systemInstruction: systemParts.length > 0 ? systemParts.join('\n\n') : undefined,
  };
}

/**
 * Convert OpenAI-style tool definitions to Vertex AI tool declarations.
 *
 * OpenAI format:
 *   { type: 'function', function: { name, description, parameters } }
 *
 * Vertex AI format:
 *   { functionDeclarations: [{ name, description, parameters }] }
 */
export function openAiToolsToVertex(
  openAiTools: Array<{
    type: string;
    function: { name: string; description: string; parameters: Record<string, unknown> };
  }>
): VertexTool[] {
  if (!openAiTools || openAiTools.length === 0) return [];

  const functionDeclarations: VertexFunctionDeclaration[] = openAiTools
    .filter((t) => t.type === 'function')
    .map((t) => ({
      name: t.function.name,
      description: t.function.description,
      parameters: t.function.parameters,
    }));

  if (functionDeclarations.length === 0) return [];

  return [{ functionDeclarations }];
}
